# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-25 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='type',
            new_name='types',
        ),
    ]
